### ISSUE TITLE
Removing flot.js & related

### ISSUE THREAD

**Issue by MFlyer** [rockstor/rockstor-jslibs#10]
Hi @schakrava & @priyaganti,
actually on my side there's no more need of flot.js libs
Had a `grep -Rl flot` to check is we're still using it, but got results only from `base.html` and `setup.html`
```html
    <script src="/static/js/lib/jquery.flot.js"></script>
    <script src="/static/js/lib/jquery.flot.navigate.js"></script>
    <script src="/static/js/lib/jquery.flot.resize.js"></script>
    <script src="/static/js/lib/jquery.flot.stack.js"></script>
    <script src="/static/js/lib/jquery.flot.tooltip_0.5.js"></script>
    <script src="/static/js/lib/jquery.flot.axislabels.js"></script>
    <script src="/static/js/lib/jquery.flot.stackpercent.js"></script>
    <script src="/static/js/lib/jquery.flot.time.js"></script>
```
In addition to having some "random tests" over Rockstor pages, for all I know that lib was used only on Widgets, can you confirm this? Removing flot 8 js libs will make Rockstor at least a little lighter

BR
Mirko

**Comment by phillxnet** [comment]
This issue depends on the now linked rockstor-core issue of:
"Remove redundant jquery.flot - rockstor-jslibs related": https://github.com/rockstor/rockstor-core/issues/2448
